language: python
dist: bionic
env:
  - DEBUG=true
services:
  - xvfb
  - pulse
python:
 - 3.6
 - 3.8
before_install:
 - python --version
 - pip install -U pip
 - pip install -U pytest
 - pip install praw pyqt5 requests pillow PyQtWebEngine wget ffmpeg-python python-vlc
 - sudo apt-get -y install libqt5gui5 ffmpeg apulse libpulse-mainloop-glib0 pulseaudio
install:
 - make
 - make install
script:
 - make test
