language: python
dist: bionic
env:
  - QT_DEBUG_PLUGINS=1
services:
  - xvfb
python:
 - 3.5
 - 3.6
 - 3.8
before_install:
 - python --version
 - pip install -U pip
 - pip install -U pytest
 - pip install codecov
 - pip install praw pyqt5 requests pillow
 - sudo apt-get -y install libqt5gui5
install:
 - make
 - make install
script:
 - make test
 - codecov
